// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package admrptservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdmRptServiceClient is the client API for AdmRptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdmRptServiceClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type admRptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmRptServiceClient(cc grpc.ClientConnInterface) AdmRptServiceClient {
	return &admRptServiceClient{cc}
}

func (c *admRptServiceClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/admrptservice.AdmRptService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmRptServiceServer is the server API for AdmRptService service.
// All implementations must embed UnimplementedAdmRptServiceServer
// for forward compatibility
type AdmRptServiceServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedAdmRptServiceServer()
}

// UnimplementedAdmRptServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdmRptServiceServer struct {
}

func (UnimplementedAdmRptServiceServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAdmRptServiceServer) mustEmbedUnimplementedAdmRptServiceServer() {}

// UnsafeAdmRptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmRptServiceServer will
// result in compilation errors.
type UnsafeAdmRptServiceServer interface {
	mustEmbedUnimplementedAdmRptServiceServer()
}

func RegisterAdmRptServiceServer(s grpc.ServiceRegistrar, srv AdmRptServiceServer) {
	s.RegisterService(&AdmRptService_ServiceDesc, srv)
}

func _AdmRptService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmRptServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admrptservice.AdmRptService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmRptServiceServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// AdmRptService_ServiceDesc is the grpc.ServiceDesc for AdmRptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdmRptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admrptservice.AdmRptService",
	HandlerType: (*AdmRptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _AdmRptService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admrptservice/admrptservice.proto",
}
